import { GENERAL_MESSAGE } from '../config/messages'
import { INSTAGRAM_URL, TIKTOK_URL } from '../config/social'
import WhatsAppButton from '../components/WhatsAppButton'

const ADDRESS = 'Olutola Gate, opposite Miliki FM, Ojodu Berger, Lagos, Nigeria'
const MAP_EMBED_URL = 'https://www.google.com/maps?q=' + encodeURIComponent(ADDRESS) + '&output=embed'
const DIRECTIONS_URL = 'https://www.google.com/maps/search/?api=1&query=' + encodeURIComponent(ADDRESS)

function Contact() {
return (

<div className="bg-pwesh-paper text-pwesh-ink"> <section className="mx-auto max-w-6xl px-6 py-16 md:py-24"> <p className="text-xs font-semibold uppercase tracking-widest text-pwesh-purple motion-safe:animate-fade-up">Contact us</p> <h1 className="mt-4 font-display text-5xl font-bold leading-[1.05] text-pwesh-night md:text-7xl motion-safe:animate-fade-up motion-safe:[animation-delay:100ms]">Let us <em className="italic text-pwesh-purple">talk.</em></h1> <p className="mt-6 max-w-2xl text-base leading-relaxed md:text-lg motion-safe:animate-fade-up motion-safe:[animation-delay:250ms]">Whether you are coming for a service, a consultation or training, send us a message on WhatsApp or come by the studio.</p> <div className="mt-8 motion-safe:animate-fade-up motion-safe:[animation-delay:400ms]"> <WhatsAppButton message={GENERAL_MESSAGE} label="Chat on WhatsApp" /> </div> </section> <section className="mx-auto max-w-6xl px-6 pb-16 md:pb-24"> <div className="grid gap-10 md:grid-cols-2 md:gap-14"> <div> <p className="text-xs font-semibold uppercase tracking-widest text-pwesh-purple">Find us</p> <h2 className="mt-4 font-display text-3xl font-bold text-pwesh-night md:text-5xl">The studio</h2> <p className="mt-4 leading-relaxed">{ADDRESS}</p> <a href={DIRECTIONS_URL} target="_blank" rel="noopener noreferrer" className="mt-3 inline-block font-semibold text-pwesh-purple underline underline-offset-4 transition-colors hover:text-pwesh-night">Get directions</a> <p className="mt-10 text-xs font-semibold uppercase tracking-widest text-pwesh-purple">Opening days</p> <p className="mt-3 text-lg font-semibold text-pwesh-night">Monday - Friday</p> <p className="mt-1">9:00 AM - 7:00 PM</p> <p className="mt-10 text-xs font-semibold uppercase tracking-widest text-pwesh-purple">Follow us</p> <div className="mt-4 flex flex-wrap gap-4"> <a href={INSTAGRAM_URL} target="_blank" rel="noopener noreferrer" className="rounded-full border border-pwesh-purple px-6 py-3 text-sm font-semibold text-pwesh-purple transition-colors hover:bg-pwesh-purple hover:text-white">Instagram</a> <a href={TIKTOK_URL} target="_blank" rel="noopener noreferrer" className="rounded-full border border-pwesh-purple px-6 py-3 text-sm font-semibold text-pwesh-purple transition-colors hover:bg-pwesh-purple hover:text-white">TikTok</a> </div> </div> <div className="overflow-hidden rounded-2xl bg-pwesh-lilac"> <iframe title="PWESH BEAUTY HUB location on Google Maps" src={MAP_EMBED_URL} className="h-80 w-full md:h-full md:min-h-[26rem]" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen ></iframe> </div> </div> </section> </div> ) }

export default Contact